name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  TAG_NAME: $(date +%s)
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/fleetmixer/mariadb:${{ github.sha }}
    - name: Login to ghcr.io 
      run: echo $GITHUB_TOKEN | docker login ghcr.io -u fleetmixer --password-stdin
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Push the Docker image latest  
      run: docker push ghcr.io/fleetmixer/mariadb:latest
    - name: Push the Docker image with version string  
      run: docker push ghcr.io/fleetmixer/mariadb:${{ github.sha }}
      
